---
title: "504 Projects"
author: "Diana Liang"
date: "2/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(survival)
library(ggplot2)
library(gbm)
```

# COMPAS Recidivism Scores by Gender
```{r data}
data <- read.csv("https://raw.githubusercontent.com/propublica/compas-analysis/master/cox-violent-parsed.csv")
data <- as.data.frame(data)

dat <- data %>%
  group_by(id) %>%
  filter(row_number()==1)%>%
  ungroup() %>%
  mutate(time_risk = end-start) %>%
  filter(time_risk > 0) %>%
  filter(v_decile_score >= 1) %>%
  select(id, sex, is_violent_recid,
         v_decile_score, v_score_text, time_risk)
dat <- dat[complete.cases(dat),]

```
```{r survival}
surv_obj <- with(dat, Surv(time_risk, is_violent_recid))

score_model <- coxph(surv_obj~v_decile_score*sex, data=dat)

cat_model <- coxph(surv_obj~v_score_text*sex, data=dat)
```
```{r tables}
score_table <- data.frame(risk_coef = summary(score_model)$coef[,2],
                          lower_95 = exp(confint(score_model))[,1],
                          upper_95 = exp(confint(score_model))[,2],
                          p_value = summary(score_model)$coef[,5]) %>%
  transmute(variables = row.names(summary(score_model)$coef),
            risk_coef = sprintf("%0.3f (%0.3f, %0.3f)", risk_coef, lower_95, upper_95),
            p_value = sprintf("%0.3f", p_value))
knitr::kable(score_table,
             col.names=c("Variables", "Prop. Risk", "P-value"), 
             caption="Proportional Risk of Recidivism compared to Female with 95% Conf. Int (Using Decile Score)")

cat_table <- data.frame(risk_coef = summary(cat_model)$coef[,2],
                          lower_95 = exp(confint(cat_model))[,1],
                          upper_95 = exp(confint(cat_model))[,2],
                          p_value = summary(cat_model)$coef[,5]) %>%
  transmute(variables = row.names(summary(cat_model)$coef),
            risk_coef = sprintf("%0.3f (%0.3f, %0.3f)", risk_coef, lower_95, upper_95),
            p_value = sprintf("%0.3f", p_value))
knitr::kable(cat_table,
             col.names=c("Variables", "Prop. Risk", "P-value"), 
             caption="Proportional Risk of Recidivism compared to High Scored Female with 95% Conf. Int. (Using Decile Score Category)")
```
```{r plots}
score_new_values <- data.frame(v_decile_score = rep(c(1:10), 2),
                         sex = rep(c("Male", "Female"), each=10))
score_new_values$sex <- as.factor(score_new_values$sex)
score_new_values$pred <- predict(score_model, newdata=score_new_values)
ggplot(data=score_new_values, aes(x=v_decile_score, y=exp(pred), group=sex)) +
  labs(title = "Effect of Violent Decile Score on Recidivism Risk by Sex",
       x = "Violent Decile Score",
       y = "Predicted Proportional Risk of Recidivism") +
  geom_line(aes(color=sex)) +
  geom_point(aes(color=sex)) + theme(plot.title = element_text(size=11))

cat_new_values <- data.frame(v_score_text = rep(c("Low", "Medium", "High", "N/A"), 2),
                         sex = rep(c("Male", "Female"), each=4))
cat_new_values$v_score_text <- as.factor(cat_new_values$v_score_text)
cat_new_values$sex <- as.factor(cat_new_values$sex)
cat_new_values$pred <- predict(cat_model, newdata=cat_new_values)
ggplot(data=cat_new_values, aes(x=v_score_text, y=exp(pred), group=sex)) +
  labs(title = "Effect of Violent Decile Category on Recidivism Risk by Sex",
       y = "Predicted Proportional Risk of Recidivism") +
  geom_point(aes(color=sex)) +
  geom_line(aes(color=sex)) +
  scale_x_discrete(name ="Violent Decile Category", 
                    limits = c("Low","Medium","High", "N/A")) +
  theme(plot.title = element_text(size=11))

```

# Causal Inference of Absences on Math Scores
```{r}
## Data cleaning-----------------------------------------------------------
data <- read.csv("student-mat.csv", sep=";")
data <- data %>%
  select(-G1, -G2) %>%
  filter(G3 > 0)
data$absent <- ifelse(data$absences >= 3, "Treatment", "Control")
data$absent <- as.factor(data$absent)
data$macol<-ifelse(data$Medu == 4, 1, 0)
data$macol <- as.factor(data$macol)
data$pacol<-ifelse(data$Fedu == 4, 1, 0)
data$pacol <- as.factor(data$pacol)
data$close <- ifelse(data$traveltime <= 1 , 1, 0)
data$close <- as.factor(data$close)
data$studytime <-ifelse(data$studytime <= 2 , 1, 0)
data$studytime <- as.factor(data$studytime)

data <- data %>%
  select(school, sex, age, address, famsize, Pstatus, schoolsup,
         famsup, activities, nursery, higher, internet, romantic,
         famrel, freetime, goout, Dalc, Walc, health, macol, pacol,
         close, G3, absent)

## Creating baseline table-------------------------------------------------
baseline <- matrix(NA, ncol=4, nrow=23)
for(i in 1:(ncol(data)-1)){
  if(is.factor(data[,i]) == TRUE){
    temp <- table(data[,i], data$absent)
    temp <- rbind(temp, temp[1,]+temp[2,])
    temp <- cbind(temp[,1]+temp[,2], temp)
    temp <- as.vector(temp[1,]*100/temp[3,])
    temp <- paste0(sprintf("%0.1f", temp), "%")
    p_val <- chisq.test(data[,i], data$absent)$p.value
    temp <- c(temp, sprintf("%0.3f", p_val))
  } 
  else{
    temp_c <- data[,i][data$absent=="Control"]
    temp_t <- data[,i][data$absent=="Treatment"]
    temp_mean <- c(mean(data[,i]), mean(temp_c),
                   mean(temp_t))
    temp_sd <- c(sd(data[,i]), sd(temp_c),
                  sd(temp_t))
    temp <- sprintf("%0.1f(%0.2f)", temp_mean, temp_sd)
    p_val <- chisq.test(data[,i], data$absent)$p.value
    temp <- c(temp, sprintf("%0.3f", p_val))
  }
  baseline[i,] <- temp
}
baseline <- data.frame("Variable" = colnames(data)[1:23],
                       "Total (357)" = baseline[,1],
                       "Control (145)" = baseline[,2],
                       "Treatment (212)" = baseline[,3],
                       "p-value" = baseline[,4])
knitr::kable(baseline, caption="Baseline Characteristics")

## Logistic Weights--------------------------------------------------------
prop.mod <- glm(absent ~ school + sex + age + address + 
                  famsize + Pstatus  + schoolsup + famsup + 
                  activities + nursery + higher + internet + 
                  romantic + famrel + freetime + goout + 
                  Dalc + Walc + health, 
                data=data, family=binomial())
summary(prop.mod)

treat_prop <- predict(prop.mod, newdata = data[,-23],
                      type = 'response')
data$logistic_prop <- treat_prop
data$logistic_weight <- ifelse(data$absent == "Treatment",
                               1/(1-treat_prop), 1/treat_prop)
boxplot(treat_prop ~ absent, data=data)
glm1 <- glm(G3 ~ absent, weights = logistic_weight, data = data)
summary(glm1)

## Boosting Weights--------------------------------------------------------
data$absent <- ifelse(data$absent=="Treatment", 1, 0)
boosted.mod <- ps(absent ~ school + sex + age + address + 
                    famsize + Pstatus  + schoolsup + famsup + 
                    activities + nursery + higher + internet + 
                    romantic + famrel + freetime + goout + 
                    Dalc + Walc + health, 
                  data=data,
                  estimand = "ATE",
                  n.trees = 5000, 
                  interaction.depth=2, 
                  perm.test.iters=0, 
                  verbose=FALSE, 
                  stop.method = c("es.mean"))
summary(boosted.mod)
summary(boosted.mod$gbm.obj,
        n.trees=boosted.mod$desc$es.mean.ATE$n.trees, 
        plot=FALSE)
data$boosted <- get.weights(boosted.mod)
plot(boosted.mod, plots=3)
bal.table(boosted.mod)
glm2 <- glm(G3 ~ absent, weights = boosted, data = data)
summary(glm2)
```